// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditTaskController from "./edit_task_controller"
application.register("edit-task", EditTaskController)

import EventSubscriptionController from "./event_subscription_controller"
application.register("event-subscription", EventSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
